l_hip_pitch:
  return_delay_time: 1
l_hip_roll:
  return_delay_time: 1
l_hip_yaw:
  return_delay_time: 1
l_knee:
  return_delay_time: 1
l_ank_pitch:
  return_delay_time: 1
l_ank_roll:
  return_delay_time: 1
r_hip_pitch:
  return_delay_time: 1
r_hip_roll:
  return_delay_time: 1
r_hip_yaw:
  return_delay_time: 1
r_knee:
  return_delay_time: 1
r_ank_pitch:
  return_delay_time: 1
r_ank_roll:
  return_delay_time: 1
